# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Add app version git tag to latest commit"
  lane :add_version_tag do
    version = get_version_number(
      xcodeproj: "TestGithubActions.xcodeproj",
      target: "TestGithubActions"
    )

    tag_name = "v#{version}-#{Time.now.getlocal("+09:00").strftime("%Y%m%d-%H%M%S-JST")}"
    
    add_git_tag(
      tag: tag_name
    )

    ENV["TAG_NAME"] = tag_name
  end
end
