name: Add git tag

on:
  workflow_dispatch:

 jobs:
   create-git-tag:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - run: |
           echo "v1-$(TZ=Asia/Tokyo date +%Y%m%d-%H%M%S)" > TAG_NAME
           git tag $(cat TAG_NAME)
           git push origin $(cat TAG_NAME)
